apiVersion: v1
clusters:
  - cluster:
      server: __OPENSHIFT_API_URL__
      insecure-skip-tls-verify: true
    name: cluster
contexts:
  - context:
      cluster: cluster
      namespace: default
      user: __OPENSHIFT_API_USER__/cluster
    name: default/cluster/__OPENSHIFT_API_USER__
current-context: default/cluster/__OPENSHIFT_API_USER__
kind: Config
preferences: {}
users:
  - name: __OPENSHIFT_API_USER__/cluster
    user:
      token: __OPENSHIFT_API_TOKEN__
