apiVersion: v1
kind: Pod
metadata:
  name: ds-testsuite-__ID__
  namespace: __OPERATORS_NS__
spec:
  volumes:
    - name: test-run-results
    - name: kubeconfig
      configMap:
        name: ds-testsuite-kubeconfig
  containers:
    # container containing the tests
    - name: test
      image: quay.io/devspaces/ds-interop-tests:latest
      args:
        - "--devspaces-namespace=__DEVSPACES_NS__"
        - "--operators-namespace=__OPERATORS_NS__"
        - "--user-namespace=__USER_NS__"
        - "--subscription-name=devspaces"
        - "--channel=stable"
        - "--source-ns=openshift-marketplace"
        - "--catalog-name=redhat-operators"
        - "--package-name=devspaces"
        - "--csv-name=__DEV_SPACES_VERSION__"
      imagePullPolicy: Always
      env:
        - name: OPERATORS_NAMESPACE
          value: __OPERATORS_NAMESPACE__
        - name: KUBECONFIG
          value: /tmp/kubeconfig/config
      volumeMounts:
        - name: test-run-results
          mountPath: /test-run-results
        - name: kubeconfig
          mountPath: /tmp/kubeconfig
    # the container used to download the test results
    - name: download
      image: quay.io/crw_pr/rsync:latest
      volumeMounts:
        - name: test-run-results
          mountPath: /test-run-results
      command: ["sh"]
      args:
        [
          "-c",
          "while true; if [[ -f /tmp/done ]]; then exit 0; fi; do sleep 1; done",
        ]
  restartPolicy: Never
